import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  Header,
  Container,
  Footer,
  Subscriber,
  PageHeader,
} from "./components";

import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          "mx-auto flex max-w-wrapper-page-sz flex-col items-center justify-start p-2xl",
        )}
      >
        <Header />
        <main className="flex min-h-screen w-full flex-col items-center justify-start">
          <Container width="xl">
            <PageHeader
              title="Do you like this Stories ?"
              text="Take a moment to explore our collection of posts and discover the
          simplicity within."
            />
            {children}
          </Container>
        </main>
        <Container width="xl">
          <Subscriber />
        </Container>
        <Footer />
      </body>
    </html>
  );
}
